version: '3'
services:

    app_jenkins:
        image: "jenkins:latest"
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - "./data/jenkins/:/var/jenkins_home/"

    app_gitlab:
        image: "gitlab/gitlab-ce:latest"
        ports:
            - "22:22"
            - "80:80"
            - "443:443"
        volumes:
            - "./config/gitlab/:/etc/gitlab/"
            - "./log/gitlab/:/var/log/gitlab/"
            - "./data/gitlab/:/var/opt/gitlab/"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://git.example.com'
                gitlab_rails['time_zone']                 = 'Asia/Shanghai'
                gitlab_rails['smtp_enable']               = true
                gitlab_rails['smtp_address']              = 'smtp.gmail.com'
                gitlab_rails['smtp_port']                 = 587
                gitlab_rails['smtp_user_name']            = 'user@gmail.com'
                gitlab_rails['smtp_password']             = 'password'
                gitlab_rails['smtp_domain']               = 'gmail.com'
                gitlab_rails['smtp_authentication']       = 'plain'
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls']                  = true

    app_gogs:
        image: "gogs/gogs:latest"
        ports:
            - "22:22"
            - "3000"
        volumes:
            - "/tmp/:/tmp/"
            - "./log/gogs/:/app/gogs/log/"
            - "./data/gogs/:/data/"
        restart: "always"

    app_sftp:
        image: "atmoz/sftp"
        ports:
            - "2223:22"
        volumes:
            - "./config/sftp/users.conf:/etc/sftp/users.conf"
            - "../web/www/:/home/user/"
            - "./config/sftp/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key"
            - "./config/sftp/ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub"
        restart: "always"
